// Generated by CoffeeScript 1.9.3
var Express, app, combo, compression, config, errorHandler, methodOverride, morgan;

Express = require('express');

morgan = require('morgan');

methodOverride = require('method-override');

errorHandler = require('errorhandler');

compression = require('compression');

combo = require('static-combo-handler');

config = require('./config.json');

app = Express();

app.set('port', process.env.PORT || config.port);

app.use(compression());

app.use(morgan('dev'));

app.use(methodOverride());

app.use(Express.query());

app.use(errorHandler());

app.use(Express["static"](config.assetsPath, {
  "maxage": Infinity,
  "setHeaders": function(res, path) {
    return res.setHeader("Access-Control-Allow-Origin", "*");
  }
}));

app.use(combo(config));

app.listen(app.get('port'), function() {
  return console.log("Express Assests Combo Service run at " + app.get('env') + " listening on port: " + app.get('port'));
});
